### ISSUE TITLE
Weird formatting on <i> tags with ERB (e.g. used for icons)

### ISSUE THREAD

**Issue by julienma** [adamzapasnik/prettier-plugin-erb#36]
Hey,
This is a great plugin, thanks.

I have a weird issue with some icons using `<i>` tags when there is an `aria-` attribute, and some ERB immediately following.

Most are a non-issue, meaning than Prettier does not change anything:

```html
<!-- No changes here -->
<i class="far fa-file-upload fa-2x"></i>
```

However I have some other icons which are weirdly formatted, with a line break in the middle of the closing `</i>` tag. This seems to happen when there are additional attributes (e.g. `aria-`) and ERB tags around. Here are the diff of some tests I made:

```diff
ERB + ARIA: this is wrong, notice the linebreak in the middle of the closing tag </i>:
-<li class="c-sb-list-item"><span class="muted">
-  <% if @customer.name.present? %>
-  <i class="icon-person icon-sb" aria-hidden="true"></i><%= @customer.name %>
-  <% end %>
-</span></li>
+<li class="c-sb-list-item">
+  <span class="muted">
+    <% if @customer.name.present? %>
+      <i class="icon-person icon-sb" aria-hidden="true"></i
+      ><%= @customer.name %>
+    <% end %>
+  </span>
+</li>

All the following examples are working as expected:
===================================================

ERB / NO ARIA:
-<li class="c-sb-list-item"><span class="muted">
-  <% if @customer.name.present? %>
-  <i class="icon-person icon-sb"></i><%= @customer.name %>
-  <% end %>
-</span></li>
+<li class="c-sb-list-item">
+  <span class="muted">
+    <% if @customer.name.present? %>
+      <i class="icon-person icon-sb"></i><%= @customer.name %>
+    <% end %>
+  </span>
+</li>
 
NO ERB / ARIA:
-<li class="c-sb-list-item"><span class="muted">
-  <i class="icon-person icon-sb" aria-hidden="true"></i>
-</span></li>
+<li class="c-sb-list-item">
+  <span class="muted">
+    <i class="icon-person icon-sb" aria-hidden="true"></i>
+  </span>
+</li>
 
NO ERB / NO ARIA:
-<li class="c-sb-list-item"><span class="muted">
-  <i class="icon-person icon-sb"></i>
-</span></li>
+<li class="c-sb-list-item">
+  <span class="muted">
+    <i class="icon-person icon-sb"></i>
+  </span>
+</li>

Alternatives with a linebreak between <i> and ERB (also working examples):
==========================================================================

ALT - ERB + ARIA:
-<li class="c-sb-list-item"><span class="muted">
-  <% if @customer.name.present? %>
-  <i class="icon-person icon-sb" aria-hidden="true"></i>
-  <%= @customer.name %>
-  <% end %>
-</span></li>
+<li class="c-sb-list-item">
+  <span class="muted">
+    <% if @customer.name.present? %>
+      <i class="icon-person icon-sb" aria-hidden="true"></i>
+      <%= @customer.name %>
+    <% end %>
+  </span>
+</li>
 
ALT - ERB / NO ARIA:
-<li class="c-sb-list-item"><span class="muted">
-  <% if @customer.name.present? %>
-  <i class="icon-person icon-sb"></i>
-  <%= @customer.name %>
-  <% end %>
-</span></li>
+<li class="c-sb-list-item">
+  <span class="muted">
+    <% if @customer.name.present? %>
+      <i class="icon-person icon-sb"></i>
+      <%= @customer.name %>
+    <% end %>
+  </span>
+</li>
```

**Comment by adamzapasnik** [comment]
Hey @julienma Apologies for replying so late, I thought I have added a comment :facepalm: 
I'm afraid that's how prettier formats it by default, check here: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgSwARnQQwGdCBeAHXAFpCAjSrQmSzeAWwoD4ypttVCADvh54ipCqwCu8ACaduvRahmYAblx6K+OUcXIhMkKJQFwAToWjZD0SmfsPHTgOavXTj09qdUAekwcqJiszti+Glp+KuoKfL6Cwhp+WBwgADQgEAIwmNCEyKD49hAA7gAKRQj5KPjoJfgAnvkZNGb4YADWcDAAykJgmFDOyDBmknAZcKw0cDIyswAyws6S+M5wAGIQZqz4MDlDyCD40hDpIAAWMKzoAOoXLHAJYHA9VSxqLA1HYMTng4RzDAym1nLtkAAzWqAjIAK0IAA8AEJtTrdHr4VhwBaDOCQ6ETEDwhE9QbOdBwACKkgg8Hx6BhICEFnMRyuN3OAjMgxgt0wMhgF2QAA4AAwZLkQQG3NoCI5cp7mVR4jIARxp8BBWWqx0IlCgcFms3OZjg6swppBa3BSChDMJgNYmBGYwdZIp1NpeNtBIyMHwND5AqFSAATH62pgsEMAMIQVg2kBPACs50kgIAKgHqnbGapxgBJKDzWA9MDc7IAQWLPRgDQp9MBAF8m0A

I will try to explain. It's not related to aria. It happens because right after `</i>` there is an expression, so prettier doesn't (for some reason) input a white space between two of them. In the examples with aria it happens because a line exceeds `printWidth` value and prettier wraps that line.

**Comment by julienma** [comment]
Ok, thanks for the details @adamzapasnik.
I've submitted an issue at Prettier: https://github.com/prettier/prettier/issues/10872

**Comment by julienma** [comment]
Well well, ok, it seems this is intended: https://github.com/prettier/prettier/issues/10872#issuecomment-840577316

Let's close this issue then.
